### ISSUE TITLE
[dev][biocswirl][dbg] Add Basic DockerFile 

### ISSUE THREAD

**Issue by lisancao** [biocswirl-dev-team/dev_setup#2]
# [dev][biocswirl][dbg] Add Basic DockerFile 

# Tasks 
- [ ] Add a DockerFile that includes basic R and Bioconductor 
- [ ] Has R packages or freshly installs Swirl 
- [ ] Basic user environment and directory 

# Resources
https://o2r.info/2017/05/30/containerit-package/
https://haoye.us/post/2019-10-10-docker-for-r-package-development/
https://github.com/Bioconductor/bioconductor_docker

# Tag can be 
    biocswirl(related to course material)
    biocterm (interface changes)
    dev      (developers only)
    file     (changes to file and folder structuring) 
    rpkg     (r package/usethis and CRAN documentation changes)
    feat     (new feature)
    fix      (bug fix)
    refactor (refactoring code)
    style    (formatting, missing semi colons, etc; no code change)
    doc      (changes to documentation)
    test     (adding or refactoring tests; no production code change)
    version  (version bump/new release; no production code change)
    dbg      (Changes in debugging code/frameworks; no production code change)
    license  (Edits regarding licensing; no production code change)
    hack     (Temporary fix to make things move forward; please avoid it)
    WIP      (Work In Progress; for intermediate commits to keep patches reasonably sized)
